/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AutoPause: typeof import('./src/components/Settings/AutoPause.vue')['default']
    AutoResume: typeof import('./src/components/Settings/AutoResume.vue')['default']
    HR: typeof import('./src/components/Settings/HR.vue')['default']
    PauseRow: typeof import('./src/components/Settings/PauseRow.vue')['default']
    ResetButton: typeof import('./src/components/Settings/ResetButton.vue')['default']
    ResumeTooltip: typeof import('./src/components/ResumeTooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionBreakSliders: typeof import('./src/components/Settings/SessionBreakSliders.vue')['default']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    VersionAlert: typeof import('./src/components/VersionAlert.vue')['default']
  }
}
